### ISSUE TITLE
move to netstandard 2.0 for maximum backwards compatibility

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/DeedleExtensions#6]
This package also does not work in a netstandard/net5 only environment:

![image](https://user-images.githubusercontent.com/21338071/112326327-b692ad80-8cb4-11eb-851e-2cbc4bcc8cf7.png)

**Comment by HLWeil** [comment]
Fixed and published in fd3648b8aab4c0a4959edca52a19c3a47979f604
